# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello-world"
  hello-world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  build-grpc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: |
          export MY_INSTALL_DIR=$HOME/.local
          mkdir -p $MY_INSTALL_DIR
          export PATH="$MY_INSTALL_DIR/bin:$PATH"
          
      - name: Install cmake
        run: |
          sudo apt install -y cmake
          cmake --version
          
      - name: Install other required tools
        run: sudo apt install -y build-essential autoconf libtool pkg-config
        
      - name: Clone the grpc repo
        run: git clone --recurse-submodules -b v1.50.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc
        
      - name: Build and install gRPC and Protocol Buffers
        run: |
          cd grpc
          mkdir -p cmake/build
          pushd cmake/build
          cmake -DgRPC_INSTALL=ON \
            -DgRPC_BUILD_TESTS=OFF \
            -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
            ../..
          make -j 4
          sudo make install
          popd
          
      - name: Build the example
        run: |
          cd grpc
          cd examples/cpp/helloworld
          mkdir -p cmake/build
          pushd cmake/build
          cmake -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR ../..
          make -j 4
          
